# Generated by Django 5.2.14 on 2026-05-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('uploaded_file', models.FileField(upload_to='documents/')),
                ('raw_text', models.TextField()),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
    ]
