# Generated by Django 5.2.14 on 2026-05-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LLM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='raw_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
