# Generated by Django 5.2.14 on 2026-05-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LLM', '0002_alter_documents_raw_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
