# Generated by Django 5.2.14 on 2026-05-31 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LLM', '0003_alter_documents_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='raw_text',
        ),
        migrations.AlterField(
            model_name='documents',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
