# Generated by Django 5.2.14 on 2026-06-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LLM', '0004_remove_documents_raw_text_alter_documents_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='chroma_uuid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
