# Generated by Django 5.2.14 on 2026-06-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LLM', '0005_documents_chroma_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='raw_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='title',
            field=models.CharField(default='sample.docx', max_length=255, unique=True),
        ),
    ]
