# Generated by Django 5.2.14 on 2026-06-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LLM', '0006_documents_raw_text_alter_documents_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryAndAwnser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(blank=True, null=True)),
                ('awnser', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
