# Generated by Django 5.2.14 on 2026-06-01 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LLM', '0007_queryandawnser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QueryAndAwnser',
            new_name='QueryAndAnswer',
        ),
    ]
