# Generated by Django 5.2.14 on 2026-06-02 21:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LLM', '0008_rename_queryandawnser_queryandanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documents',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='queryandanswer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
